xboard:
  provider: mihomo
  
  remote_config:
    sources:
      - name: redirect
        url: https://nodesfree.github.io/v2raynode/config.json
        priority: 100
    timeout_seconds: 10
    max_retries: 3
  
  log:
    enabled: true
    level: info
